---
- name: Override kubernetes facts
  include: override_facts.yml

- name: Configure kubernetes
  include: configure.yml
  tags: configure

- include: secrets.yml
  tags:
    secrets
  tags: configure
