---
# Deploy Analytics environment.

- include: Playbooks/extra_server.yml
  tags:
    - aux_server

- include: Playbooks/gitlab.yml
  tags:
    - gitlab

- include: Playbooks/k8s.yml
  tags:
    - k8s
