---
# Install Flannel.

- name: Install Flannel with package manager
  package:
    name=flannel
    state=latest
  when: not is_atomic

- name: Set Flannel config file directory
  set_fact:
    flannel_config_dir: "/etc/sysconfig"

- name: Create config file directory
  file: path={{ flannel_config_dir }} state=directory

- name: Install Flannel config file
  template: src=flanneld.j2 dest={{ flannel_config_dir }}/flanneld
  notify:
    - restart flannel
