---
- name: Prepare and write Flannel configuration to etcd
  include: config.yml
  delegate_to: "{{ groups['etcd'][0] }}"

- name: Install Flannel
  include: client.yml
  when: inventory_hostname in groups['masters'] + groups['nodes']

- include: firewalld.yml
  when: has_firewalld

- include: iptables.yml
  when: not has_firewalld and has_iptables

- name: Enable flannel
  service: name=flanneld enabled=yes

- name: Start flannel
  service: name=flanneld state=started
  register: flannel_started
  notify:
    - restart docker
