---
# Install kubernetes master components
- include: packageManagerInstall.yml
  when: kube_source_type == "packageManager"
  tags:
    - binary-update

- include: localBuildInstall.yml
  when: kube_source_type == "localBuild"
  tags:
    - binary-update

- include: install_rpms.yml
  when: kube_source_type == "distribution-rpm"
  tags:
    - binary-update
