---
- name: Set selinux permissive because tokens and selinux don't work together
  selinux: state=permissive policy={{ ansible_selinux.type }}
  when: ansible_selinux is defined and
        ansible_selinux.status == "enabled"

# Install kubernetes node components
- include: packageManagerInstall.yml
  when: kube_source_type == "packageManager"
  tags:
    - binary-update

- include: localBuildInstall.yml
  when: kube_source_type == "localBuild"
  tags:
    - binary-update

- include: install_rpms.yml
  when: kube_source_type == "distribution-rpm"
  tags:
    - binary-update

- name: Install kubernetes node runtime dependencies
  package:
        name: "{{ item }}"
        state: latest
  with_items:
  - socat
  - tar
  - git
  when: (kube_source_type == "localBuild" or
         kube_source_type == "github-release") and
        (ansible_distribution == "Fedora" or
         ansible_distribution == "RedHat" or
         ansible_distribution == "CentOS")

# enable cpu and memory accounting for systemd services by default
- name: Create systemd dropin directory
  file:
    path=/etc/systemd/system/system.conf.d
    state=directory mode=0755
  when: (kube_source_type == "localBuild" or
         kube_source_type == "github-release") and
        (ansible_distribution == "Fedora" or
         ansible_distribution == "RedHat" or
         ansible_distribution == "CentOS")

- name: Enable cpu and memory accounting for systemd services
  copy:
    src=kubernetes-accounting.conf
    dest="/etc/systemd/system/system.conf.d/kubernetes-accounting.conf"
  notify:
    - reload systemd
  when: (kube_source_type == "localBuild" or
         kube_source_type == "github-release") and
        (ansible_distribution == "Fedora" or
         ansible_distribution == "RedHat" or
         ansible_distribution == "CentOS")
