---

- name: init vars to select 'create' or 'deploy' ssl certificates
  set_fact:
    gitlab_deploy_self_signed_cert: false
    gitlab_create_self_signed_cert: false

- name: select 'deploy' ssl certificates
  set_fact:
    gitlab_deploy_self_signed_cert: true
  register: deploy_out
  when: "'{{ ssl_certificate }}'     != '' and
         '{{ ssl_certificate_key }}' != '' "

- name: select 'create' ssl certificates
  set_fact:
    gitlab_create_self_signed_cert: true
  when: "not {{ gitlab_deploy_self_signed_cert }}"
