---
- name: Determine if Atomic
  stat: path=/run/ostree-booted
  register: os_tree_check
  changed_when: false
  always_run: yes

- name: Set the is_atomic fact
  set_fact:
    is_atomic: true
  when: os_tree_check.stat.exists

- name: Create the directory used to store binaries
  file: path={{ bin_dir }} state=directory

- name: Create Ansible temp directory
  file: path={{ ansible_temp_dir }} state=directory

- name: Determine if has rpm
  stat: path=/usr/bin/rpm
  register: rpm_check
  changed_when: false
  always_run: yes

- name: Set the has_rpm fact
  set_fact:
    has_rpm: true
  when: rpm_check.stat.exists

# collect information about what packages are installed
- include: rpm.yml
  when: has_rpm

- include: fedora-install.yml
  when: not is_atomic and ansible_distribution == "Fedora"
