---
- name: RPM | Determine if firewalld installed
  command: "rpm -q firewalld"
  register: firewalld_check
  changed_when: false
  failed_when: false
  always_run: yes

- name: Set the has_firewalld fact
  set_fact:
    has_firewalld: true
  when: firewalld_check.rc == 0

- name: Start firewalld service
  service:
    name=firewalld
    state=started
    enabled=yes
  when: has_firewalld

- name: Determine if iptables-services installed
  command: "rpm -q iptables-services"
  register: iptables_check
  changed_when: false
  failed_when: false
  always_run: yes

- name: Set the has_iptables fact
  set_fact:
    has_iptables: true
  when: iptables_check.rc == 0

- name: Start iptables service
  service:
    name=iptables
    state=started
    enabled=yes
  when: has_iptables
