---

# install flannel
- hosts:
  - nodes
  become: yes
  roles:
  - flannel
  tags:
  - network-service-install

# install kubernetes on the nodes
- hosts:
  - nodes
  become: yes
  roles:
  - k8s
  - k8s-node
  tags:
  - nodes

# install runtime dependencies
- hosts:
  - nodes
  become: yes
  roles:
  - epilogue
  tags:
  - epilogue
