---

# install flannel
- hosts:
  - masters
  become: yes
  roles:
  - flannel
  tags:
  - network-service-install

# install kube master services
- hosts:
  - masters
  become: yes
  roles:
  - k8s
  - k8s-master
  tags:
  - masters

# launch addons, like dns
- hosts:
  - masters
  become: yes
  roles:
  - k8s-addons
  tags:
  - addons
  - dns
