galaxy_info:
  author: Musee Ullah
  description: Install and configure SSSD for system-level LDAP authentication
  company: FireEye, Inc.
  # If the issue tracker for your role is not on github, uncomment the
  # next line and provide a value
  # issue_tracker_url: http://example.com/issue/tracker
  # Some suggested licenses:
  # - BSD (default)
  # - MIT
  # - GPLv2
  # - GPLv3
  # - Apache
  # - CC-BY
  license: MIT
  min_ansible_version: 2.0
  platforms:
  - name: EL
    versions:
    - 6
    - 7
  - name: Ubuntu
    versions:
    - trusty
    - utopic
    - vivid
  - name: Debian
    versions:
    - jessie
    - wheezy
  galaxy_tags:
    - authentication
dependencies: []
